

import Head from "next/head";
import NabvarHead from "./navbar";

export function Layout({ children }) {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <NabvarHead />
        <main>{children}</main>
    </>
  );
}

import Breadcrumb from 'react-bootstrap/Breadcrumb';

function MyBreadcrumb() {
  return (
    <Breadcrumb>
      <Breadcrumb.Item href="#">Home</Breadcrumb.Item>
      <Breadcrumb.Item href="https://getbootstrap.com/docs/4.0/components/breadcrumb/">
        Library
      </Breadcrumb.Item>
      <Breadcrumb.Item active>Data</Breadcrumb.Item>
    </Breadcrumb>
  );
}


// Generated by CodiumAI

describe('MyBreadcrumb', () => {

    // The second Breadcrumb.Item component has a 'https://getbootstrap.com/docs/4.0/components/breadcrumb/' href and displays 'Library'.
    it('should have the second Breadcrumb.Item component with "https://getbootstrap.com/docs/4.0/components/breadcrumb/" href and displaying "Library"', () => {
      const wrapper = shallow(<MyBreadcrumb />);
      const secondItem = wrapper.find(Breadcrumb.Item).at(1);
      expect(secondItem.prop('href')).toBe('https://getbootstrap.com/docs/4.0/components/breadcrumb/');
      expect(secondItem.text()).toBe('Library');
    });
});
